from random import randint

MAP_WIDTH = 50
MAP_HEIGHT = 20
GRASS = ' '
TREE = '1'
STONE = 'D'
TREASURE = 'X'
LETTER = '@'
MONSTER = '&'
USER = 'H'
SMOG = '#'
SMOG_RADIUS = 4

MAX_TREES = 500
MAX_STONES = 20
MAX_TREASURES = 7
MAX_LETTERS = MAX_TREASURES
MAX_MONSTERS = 2

ACTION_ATTACK = 1
ACTION_HEAL = 2
MAX_USER_HP = randint(700, 900)
MAX_MONSTER_HP = randint(700, 900)
